"""rename boards and tasks

Revision ID: 4f37db5b3739
Revises: 267396c7eb45
Create Date: 2024-09-21 17:22:34.197486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37db5b3739'
down_revision = '267396c7eb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position', name='user_position_uc')
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('last_edit', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_id'), ['id'], unique=False)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index('ix_boards_id')
        batch_op.drop_index('ix_boards_user_id')

    op.drop_table('boards')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_board_id')
        batch_op.drop_index('ix_tasks_id')

    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('board_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('last_edit', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_id', ['id'], unique=False)
        batch_op.create_index('ix_tasks_board_id', ['board_id'], unique=False)

    op.create_table('boards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position', name='user_position_uc')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index('ix_boards_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_boards_id', ['id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_board_id'))

    op.drop_table('task')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_user_id'))
        batch_op.drop_index(batch_op.f('ix_board_id'))

    op.drop_table('board')
    # ### end Alembic commands ###
