"""Add unique constraint on user_id and position in Boards

Revision ID: f77c66455018
Revises: 6e33fb2da3d7
Create Date: 2024-09-13 11:04:55.735883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77c66455018'
down_revision = '6e33fb2da3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('user_position_uc', ['user_id', 'position'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('user_position_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_boards_id'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
